### ISSUE TITLE
which software you use to draw Block Diagram

### ISSUE THREAD

**Issue by yueleilei** [martinribelotta/Board-RZA1L#1]
I send mail to u. can not reach.

英文说明:SMTP error, RCPT TO: Host gmail.com(74.125.127.26) RCPT TO said 550-5.1.1 The email account that you tried to reach does not exist. Please try
550-5.1.1 double-checking the recipient's email address for typos or
550-5.1.1 unnecessary spaces. Learn more at
550 5.1.1  https://support.google.com/mail/?p=NoSuchUser w10si1657182otl.39 - gsmtp

mailto:martinribelott@gmail.com

**Comment by martinribelotta** [comment]
Correct mailto: martinribelotta@gmail.com
My diagram software is draw.io

**Comment by martinribelotta** [comment]
I fix my email address in github account
